language: ruby
rvm:
- 2.6.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - release
deploy:
  provider: pages
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: master
  on:
    branch: release
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: H7gc3lLUYJ4lcqrUo9Eak9Yqhbq69cF/ghCEt5No6k9Mj88GX6PGGCAMyJL4Qxi7a+wRjb1GFcuP5PdXOXU1bIyHvvxSpnqX67Lk6sp+7roC3x1p/XgFaq9JzHJZRpR7ddEFRWsuDyVYAfTvNR0nydTnZSbR5tDkwNmASl9jBICG9XGNghjUQWPiTApidzaHs4YRSjW4zoG2/lFg8Vk7GQj0egJnNf7arqsZZM3eQV1/FVWSaM8pP0K/F9CxyxWs5D94XrZvkTn6Xcx6GPkPGLPQFMi7KLErUITOkmUwuuChf3JsxRbmNdzHshHP9koQoZXMOAEFNtwIUC9FzoCrZ+44cGBZNWIRTAkiWkoZj3oMbOZ9zH8+jzHD+eir1rhdmPFQblPCipi61VO6wERwR7YNRa1DTDDGoFFmmC4SEkSm24AgwnnNie17xam8OzqhcsvBcmF5AF747uOwBX8B1P2/gIGEaIfHyO/lITq54K7b3lG5h3iYW4IbbfmE9K2+3Rp+/Q6Wwt7Che/YXvTpRtUQZ0fw7XFIHhvi9sP3TnT8STgqMCHEisIk3hMZAyFyVZsxxPA+mvnQ01f9TvG2VyZy65UhYLIcjJp3uXZFakOZ9LCoBBG27ykLwPDmFHOHR4ni11wM+NwFfm6yui8CmFV34xs4FkMZ+38t5OdomUc=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
