language: ruby
rvm:
- 2.6.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - release
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: release
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
