language: ruby
rvm:
- 2.6.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - release
deploy:
  provider: pages
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: master
  on:
    branch: release
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: kA9CQGs8NEeE/MUAzn2XdLm/S/qOepw0AmuE2If1ErTO9NsC+ViMkYLDdSmiwqTh6Q8FDnA9/Aw32h11OlR2LYt3AZ4ka2qDG3mF7NDvMkkJlPJkTxYJ8XVxd+eMaiuKqhj+GxEfhcAzDO7xzhHArAsf1Dtwzie43d73oYbOgTPDDVhGhalRnXg0EzLT2TaaxujGgcgNNabuAX1rqiEiOcjQqtv/c90BNbQPx7ER4j6OltI0MHjhJOHJnLvz/lwB93WuKEHumzTyf8MACalEMqIRFQiSGUJt0AqwZ7g1JWdP7QMgzI+zfUisPmIv3g0hqCTEjXWs1T1Pnt6xuRrB148K466eaIt2kflsMbaTCp2E33/Yi2qDqqJXznefgftnVM1au8RALuJlNwjKzjlwMiuApf8SJt9fk/mBVLdnfvV/MNP2EwaJvh9JZKLggHu1oD/Qg4AN7JVW0JCF3cLMURLTNPlXSn20j6M5CQ0shKKtBoq7axrk79YwEMqfIWIk9zDdVzRR+KNaqj5kYQ9NB0yyYkEoU7adawj5DEYLWzeGz4IAoq6FAZ0fOkwdeXICiFN/g2xP69H0Klodnqw/ZOhIpCSgqbbT1BFB7KPDzXLbkSNYeQDYXWxEvebDfAU3rDQEsbOKSQqTWBYb9twvpSeXb++cqKx+tbqRpZzyZek=
  - secure: KkTTfIeSQtF92ljOFBwl2mpjiVzMylEmbLGaBCLs/k1hctoQNlqBgWkoUxDyvXbWofXjx7BUllZrcdGQ3oYgnXuIw6K5GIbVVlzfuilnvzIgW3h+GJNMssQ5Qh5Jz6gEELcHjjXZgLxyo9DEtmheSXWy68ycQQlnJwbRUceoN6OmkuYInrdATfALNbLSS8T/5DanCiViBiaG5173ogLEwL0mUhrQ9LVlYHG7MRW/H1kH1tUrpOH2yQNWpG7jRTUm5wpGubAa5FHE2iDKPuz1qAG2ywgMMzu/xY4Kor6gsNys9LybIj/VHxx4kNuw+yaGJ7XFptlvZ2ItjmJetRwQtBzCOYrpIkHkwGva+8x61xixdoh2xLdgfatuaSL4wsEjKjGlo9dtB6n8rZYNpkuEx9WnwEs8ZbEAYUANjJQ3GOkv2ve4JldcFicJKmzfJh/jZyX/nzYG86cOW3Lg2tyeJ1djKNEb8fUdrGR2XkSy9B+Kaf27QWRzXv/Mh0pmwy9Dxu7RclUNNtrttBbsXCbAkRFx9PR3GPFYCYFRzqCr3/NnzAoUyUpDGri293rx9dWLPwpYLfJWjoV/UHnR0xwo3xcWZ71byRCcoqIWeSFFjSR10R/ZjWifP2IWBCkLrmRQjrTGHN/pxpPahvozyKPpNT4qrngj6tNiS86rJ2UQidg=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
