# Site settings
title: Shaun Bathgate
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shaun Bathgate
user_description: Electronically founded, after a decade as a Radar Technician in the RCN and now DND, I am eager to transition into a software development role. 
user_description_1: Growing up in an entrepreneurial family, I have built a series of e-commerce websites for my family. Utilizing web hosting services such as Monster Commerce, Volusion, BigCommerce and Shopify, I would customise the front-end requirements to our specific use case. The current revisions have adopted Pixel Union templates for our 2019 modernization. 
user_description_2: More recently, I have been contributing to an Open Source non-profit Ascoderu with their email project Lokole. This has provided me with the opportunity to improve my full-stack development capabilities. The Lokole devices use Raspberry Pi's to provide affordable email capability to rural communities in Africa. Built with Python, the Lokole uses the Flask framework, interfaces with Azure cloud services and relies on tools such as Github, Travis CI, SendGrid, CloudFlare, Nginx, Docker and Kubernetes.
user_title: Junior Full Stack Developer
email: me@shaunb.ca
# twitter_username: lorem_ipsum
github_username:  sbathgate
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - src/
#   - package.json